
CREATE TABLE "MBC"."PARKING_SESSION"
(	"ID" NUMBER(19,0) NOT NULL ENABLE,
     "CAR_NO" VARCHAR2(30 CHAR),
     "CERT_APPLIED" NUMBER(1,0),
     "CERT_CODE_USED" VARCHAR2(60 CHAR),
     "CREATED_AT" TIMESTAMP (6),
     "DISCOUNT_AMOUNT" NUMBER(10,0),
     "ENTRY_AT" TIMESTAMP (6),
     "EXIT_APPROVED_AT" TIMESTAMP (6),
     "EXIT_PLANNED_AT" TIMESTAMP (6),
     "EXIT_STATUS" VARCHAR2(20 CHAR),
     "EXITED_AT" TIMESTAMP (6),
     "FEE_BEFORE" NUMBER(10,0),
     "FINAL_FEE" NUMBER(10,0),
     "FREE_MINUTES" NUMBER(10,0),
     "PARKING_ID" VARCHAR2(20 CHAR),
     "PARKING_NAME" VARCHAR2(100 CHAR),
     "PAY_STATUS" VARCHAR2(20 CHAR),
     "TOTAL_MINUTES" NUMBER(10,0),
     "UPDATED_AT" TIMESTAMP (6),
     CHECK (cert_applied in (0,1)) ENABLE,
     CHECK (exit_status in ('IN_PARKING','CALCULATED','APPROVED','EXITED','CANCELLED')) ENABLE,
     CHECK (pay_status in ('NONE','WAIVED','PAID')) ENABLE,
     PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

