CREATE TABLE "MBC"."TWOWAY_MOVIE"
(	"MDATE" DATE,
     "MPRICE" NUMBER(10,0),
     "MREADCOUNT" NUMBER(10,0),
     "MBUNHO" NUMBER(19,0) NOT NULL ENABLE,
     "MIMAGE" VARCHAR2(255 CHAR),
     "MTITLE" VARCHAR2(255 CHAR),
     "MGENRE" VARCHAR2(255 CHAR),
     PRIMARY KEY ("MBUNHO")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

